# All of the values defined in this config file can be overridden with environment variables of the same name,
# and as such will take precedence over the values defined in this file. This can be especially useful for cloud
# deployments, but you can freely choose to define the values in whichever location.
#
# Note that the type of all of the variables is enforced as it would when evaluated against the expected type
# by Python's literal_eval(...), so for example the string value of "NTBOT_SECRET_TOKEN" will have to include
# the double quotations ("token") as part of its value if using env variables. This holds true for all string
# values defined as env variables.
#
# Due to strict type checking, things like casting integer values into floats, etc, is also disallowed in the
# config. Any mismatching config types will throw an error upon launching of the bot, so this kind of
# misconfiguration should hopefully be easy enough to spot.

# The Discord bot secret token goes here. Don't share this value with others.
# For info on how to generate this token, please see: https://discord.com/developers/docs
NTBOT_SECRET_TOKEN: ""

# Name of the Discord server channel that the bot listens to.
# This value has to be an exact match of the channel name.
NTBOT_PUG_CHANNEL: pug-queue

# Number of players, total, that are required for a PUG match.
# For example, 10 for a 5v5. Needs to be an even number.
NTBOT_PLAYERS_REQUIRED_TOTAL: 10

# Debug command. Whether to allow the same player to repeatedly queue to fill up >1 slots,
# for bot testing purposes. This should normally be disabled.
NTBOT_DEBUG_ALLOW_REQUEUE: False

# How often (in seconds) to check if there's enough players pugged up to start
# playing.
NTBOT_POLLING_INTERVAL_SECS: 5

# How often (in seconds) to update the bot's Discord "presence" status message,
# displaying current amount of queued players next to the bot's nickname.
NTBOT_PRESENCE_INTERVAL_SECS: 30

# Name of the puggers role. Used for pinging.
NTBOT_PUGGER_ROLE: Puggers

# Threshold, in range of 0.0-1.0, of how many queued players are required
# for the bot to auto-ping the pugger role.
NTBOT_PUGGER_ROLE_PING_THRESHOLD: 0.5

# How long to wait, in hours, between automated "NTBOT_PUGGER_ROLE_PING_THRESHOLD"
# role pings, at a minimum. Has to be a floating point value.
NTBOT_PUGGER_ROLE_PING_MIN_INTERVAL_HOURS: 4.0

# List of 0 or more PUG queue moderator/admin roles.
# If any user should be able to do PUG queue admin tasks, use an empty value.
NTBOT_PUG_ADMIN_ROLES:
    - Admins
    - Moderators

# How long to keep idle puggers in the queue before automatically un-queueing them,
# in full hours. Has to be a positive floating point value.
NTBOT_IDLE_THRESHOLD_HOURS: 12.0

# How often can PUG queuers bulk-ping all the other players currently in the queue, in seconds.
# Admins with role(s) defined by "NTBOT_PUG_ADMIN_ROLES" are not affected by this time limit.
NTBOT_PING_PUGGERS_COOLDOWN_SECS: 600.0

# Names of each team
NTBOT_FIRST_TEAM_NAME: Jinrai
NTBOT_SECOND_TEAM_NAME: NSF

# If set to False, will publicly announce people joining and leaving the PUG queue etc,
# even if they use Discord's "silent" slash commands.
NTBOT_EPHEMERAL_MESSAGES: True

NTBOT_DB_DRIVER: "sqlite3"
NTBOT_DB_USER: "postgres"
NTBOT_DB_NAME: "postgres"
NTBOT_DB_SECRET: ""
NTBOT_DB_TABLE: "puggers"
NTBOT_DB_HOST: "localhost"
NTBOT_DB_PORT: 5432
