# Bot secret token goes here. Don't share this value with others.
# Alternatively, you can set the OS environment variable DISCORD_BOT_TOKEN,
# which will take precedence over this config value.
bot_secret_token: ""

# The first character of commands, for example "!" for "!pug"
command_prefix: "!"

# Name of the Discord server channel that the bot listens to
pug_channel_name: pug-queue

# Number of players, total, that are required for a PUG match.
num_players_required_total: 10

# Debug command. Allows the same player to repeatedly queue to fill up >1 slots.
debug_allow_requeue: False

# How often (in seconds) to check if there's enough players pugged up to start
# playing.
queue_polling_interval_secs: 5

# How often (in seconds) to update the bot's "presence" status message,
# displaying current amount of queued players next to the bot's nickname.
discord_presence_update_interval_secs: 30

# Name of the puggers role
pugger_role_name: Puggers

# Threshold, in range of 0.0-1.0, of how many queued players are required
# for the bot to auto-ping the pugger role.
pugger_role_ping_threshold: 0.5

# How long to wait, in hours, between role pings at a minimum.
pugger_role_min_ping_interval_hours: 4.0
