# Bot secret token goes here. Don't share this value with others.
# Alternatively, you can set the OS environment variable DISCORD_BOT_TOKEN,
# which will take precedence over this config value.
# For info on how to generate this token, please see: https://discord.com/developers/docs
NTBOT_SECRET_TOKEN: ""

# The first character of commands, for example "!" for "!pug"
NTBOT_CMD_PREFIX: "!"

# Name of the Discord server channel that the bot listens to.
# This value has to be an exact match of the channel name.
NTBOT_PUG_CHANNEL: pug-queue

# Number of players, total, that are required for a PUG match.
# For example, 10 for a 5v5. Needs to be an even number.
NTBOT_PLAYERS_REQUIRED_TOTAL: 10

# Debug command. Whether to allow the same player to repeatedly queue to fill up >1 slots,
# for bot testing purposes.
NTBOT_DEBUG_ALLOW_REQUEUE: False

# How often (in seconds) to check if there's enough players pugged up to start
# playing.
NTBOT_POLLING_INTERVAL_SECS: 5

# How often (in seconds) to update the bot's Discord "presence" status message,
# displaying current amount of queued players next to the bot's nickname.
NTBOT_PRESENCE_INTERVAL_SECS: 30

# Name of the puggers role. Used for pinging.
NTBOT_PUGGER_ROLE: Puggers

# Threshold, in range of 0.0-1.0, of how many queued players are required
# for the bot to auto-ping the pugger role.
NTBOT_PUGGER_ROLE_PING_THRESHOLD: 0.5

# How long to wait, in hours, between role pings at a minimum.
NTBOT_PUGGER_ROLE_PING_MIN_INTERVAL_HOURS: 4.0

# How many previous PUG channel messages to check, at most, for a previous pugger role ping.
NTBOT_PUGGER_ROLE_PING_MAX_HISTORY: 120

# List of 0 or more names of the pug maintainer roles.
# If any user should be able to do pug queue admin tasks, use an empty value.
NTBOT_PUG_ADMIN_ROLES:
    - Admins
    - Moderators

# How long to keep idle puggers in the queue before automatically un-queueing them,
# in full hours. Has to be a positive integer.
NTBOT_IDLE_THRESHOLD_HOURS: 16

# How often can PUG queuers bulk-ping all the other players currently in the queue, in seconds.
# Admins with roles defined by "pug_admin_role_name" are not affected by this time limit.
NTBOT_PING_PUGGERS_COOLDOWN_SECS: 600.0
