name: runtime validation

on:
  push:
    branches: [ main, validate_runtime ]
    paths:
      - 'runtime.txt'
      - '.github/workflows/validate_runtime.yml'
  pull_request:
    branches: [ main ]

jobs:
  validate-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: pip install semver
      - name: Validate runtime.txt
        run: |
          #!/usr/bin/env python3
          with open("runtime.txt") as f:
              lines = f.readlines()
          assert len(lines) == 1
          line = lines[0].strip()
          assert line.startswith("python-")
          semver = semver.VersionInfo.parse(line[len("python-"):])
          python_eol_limit = semver.VersionInfo.parse("3.7.0")
          assert semver >= python_eol_limit
        shell: python
